base:
  systemName: "社区系统"
  version: "0.0.1_base"
  commitID: "0bce98ce589a74dedd84c9c3d3099f1ce566afe2"
  buildTime: "2023-11-18 12:21:34"

mysql:
  ip: "mysql.test.com"
  port: 3306
  user: test
  password: test
  db: test

redis:
  ip: "redis.test.com"
  port: 6379
  password: "testredis"

mongo:
  ip: "mongo.test.com"
  port: 27017
  db: "mytest"
  user: "root"
  password: "testmongo"
